### ISSUE TITLE
can't recognize chocolate plus pedal

### ISSUE THREAD

**Issue by Hank-Chung** [Builty/TonexOneController#17]
Thanks for wonderful project.
By the way, I have a chocolate plus pedal but it can't be connected ESP32S3-Zero. I guess there's no code for that pedal and wonder you have a plan for that pedal.
Thanks

**Comment by Builty** [comment]
Hi. It should be easy enough for me to add support.
At the moment, the code is looking for the name of the device. I am looking for a better way to do this, but no solution for that yet.
If you use a phone and go to the bluetooth settings, when the Chocolate Plus is switched on, you should see the name of the device in the list. The normal Chocolate is called "FOOTCTRL" but I guess the plus is something different.
Let me know the device name, then I can add support.

**Comment by Hank-Chung** [comment]
<img width="647" alt="스크린샷 2024-11-22 오후 7 55 10" src="https://github.com/user-attachments/assets/b408edd6-c869-4fa6-9682-db5937b20c0b">

as you can see, the name of chocolate plus pedal is "FootCtrlPlus".
i'm looking forward next update. thanks.

**Comment by Builty** [comment]
Code is done and committed. I'll do some new release builds in the next few days

**Comment by Hank-Chung** [comment]
thanks for your support. i'll test when new update released and report.

**Comment by Hank-Chung** [comment]
Today, I tested new released version and confirmed it works well with my chocolate plus pedal. 
I have two ESP32-S3 based boards which one is named zero other one is super mini, and these two boards are work fine.
Thanks for your support.

**Comment by Builty** [comment]
Great, thanks for the feedback.
