### ISSUE TITLE
Waveshare Zero + MVave Chocolate latest Version not working

### ISSUE THREAD

**Issue by miasei** [Builty/TonexOneController#22]
Hello. Great project by the way. I could flash the latest client firmware on the ESP32 Zero, but the BT is not connecting. Tried the new beta in the Special folder. So now the Chocolate is connecting, but Preset changes are not possible. It is only possible to switch from A to B on Tonex One Pedal and with a step on Chocolate it changes back to A. But after that nothing else works. And I noticed that every time when I reset the Waveshare via the button the A/B of the presets on the Tonex Pedal are changed to another preset. Maybe you can help me.

**Comment by Builty** [comment]
Hi. Please set your Tonex pedal into Stomp mode. It sounds like its in A/B mode. 
The controller can only work in Stomp mode.

**Comment by miasei** [comment]
Ok. My bad! So that would be great if it is so easy. Will report if it works! Thanks for the fast reply!

**Comment by miasei** [comment]
Hey there again. Went home, stomp box on Tonex One and... yeah it is working! Thanks a lot again. Keep on the great work.

**Comment by Builty** [comment]
Great to hear!
