### ISSUE TITLE
Another case for ESP32-S3 zero-M

### ISSUE THREAD

**Issue by AlmaMaterFL** [Builty/TonexOneController#35]
Grettings,

While the case for the ESP32-S3 zero is good. I created another one in which you can click on BOOT for BOOT Mode without taking the case off. Did it for the versions with Pins, but should work for the one without them.

https://www.printables.com/model/1110479-esp32-s3-zero-m-case-pin-version

Feel free to make any changes.

Regards!

**Comment by Builty** [comment]
That looks great, thank you. I will add a link to it

**Comment by Builty** [comment]
Links added to docs. Thanks.
