### ISSUE TITLE
Uploading on Mac

### ISSUE THREAD

**Issue by DrD85** [Builty/TonexOneController#38]
I just wanted to share how you can upload easily on a Mac.
Just go to the website:
https://esp.huhn.me/
Use the files from the download in the right order and the right numbers and it flashes like a dream.
Maybe someone can provide the right settings, I have deleted the screenshot from the windows pc

**Comment by DrD85** [comment]
<img width="357" alt="image" src="https://github.com/user-attachments/assets/68f6972c-475f-4d7a-8722-deda7917a56e" />
Those are the files and settings you need to put into the website and make sure to use google Chrome or Edge

**Comment by Builty** [comment]
Wow, thank you, this is great. I can get screen shots. I will update the instructions. So much easier than using esptool via command line.

**Comment by Builty** [comment]
Docs updated. Thank you
