### ISSUE TITLE
3D Printed Case for ESP32-S3 1.69 LCD NON touch

### ISSUE THREAD

**Issue by AlmaMaterFL** [Builty/TonexOneController#39]
![1](https://github.com/user-attachments/assets/03ca8343-141d-48ca-b300-0ab3d537bded)
Greetings,

Was not able to find one so I created this case for the ESP32-S3 1.69 LCD NON touch.

https://www.printables.com/model/1114384-esp32-s3-169inch-case

Feel free to make any changes.

Regards!

**Comment by Builty** [comment]
Awesome, thank you. I will add links to it. 
I'm printing one now for myself.
Great work!

**Comment by Builty** [comment]
Docs updated. Thanks
