### ISSUE TITLE
Flashed from pre built release not working

### ISSUE THREAD

**Issue by lcollins1989** [Builty/TonexOneController#6]
Hello,

Managed to successfully flash the Waveshare board and have the screen graphics etc. It also reads when I press the footswitch on the tonex however the previous and next buttons on screen don't change the preset on the tonex, only on the waveshare screen.

Any ideas? Fresh flash?

**Comment by lcollins1989** [comment]
Update it will also show every preset as the same info.

**Comment by Builty** [comment]
Hi. Did you use V1.0.1.2? V1.0.0.2 had issues.

Is the USB connection icon on LCD grey (disconnected) or green (connected)?
If you press and hold the preset name, do you get the left/right arrows appearing?

Not sure if this is touch screen issue or USB issue.
Maybe try another USB cable. Make sure it supports data transfers and not just a charging cable. Power the Tonex off USB, without connecting 9v to it.

Hope that helps.

**Comment by lcollins1989** [comment]
Ok step by step.

Reflashed, definitely V1.0.1.2.

USB Connection icon is green.

The left/right arrows are both visible, they only change the preset number but not the image or preset 'name'

If I press and hold the preset I go into the edit menu where I can change the image, write a description etc.

I've tried 3 seperate usb cables. I believe all 3 are data cables. I've also tried the one that came with the Tonex.

Powered via usb, not the 9V.

Occasionally when scrolling through the presets it will 'jump' to a different number (from 12 to 9 for example).

When pressing the footswitch on the Tonex it will toggle between two different presets on the LCD.

**Comment by Builty** [comment]
Powered by Usb? The recommended board had 1 usb port for tonex and needs 9v power.  Is it a different t waveshare with dual usb?

**Comment by lcollins1989** [comment]
It's the same waveshare board recommended. Powered by 9v with the tonex powered and connected by usb to the waveshare.

**Comment by Builty** [comment]
Damn, sounds like everything is correct.
You running Tonex One firmware V1.1.4? 

Toggling between 2 presets on the LCD sounds like its in A/B mode. Super weird, the code forces it to stomp mode (slot C.)
Did you change the pedal back to A/B mode manually? Even that shouldn't matter.

It is very early for this project. I know of one other user who has it working OK so far.
Could be a possibility of some bugs.

**Comment by lcollins1989** [comment]
Found the issue!

For some reason the tonex wasn't in stomp mode. Works great now!

Thank you

**Comment by Builty** [comment]
Thats great! I was almost out of ideas.

I am setting the pedal to use slot C as active, but maybe there is another part of the data that sets the actual mode.
I'll create a new issue for me to investigate if I'm missing this mode selection.

**Comment by lcollins1989** [comment]
All is working as expected now I'm in stomp mode. Thanks again.
